services:
  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow/Dockerfile
    container_name: mlops-mlflow
    volumes:
      - ./data/mlflow-data:/mlflow-data
    environment:
      MLFLOW_BACKEND_STORE_URI: /mlflow-data
      MLFLOW_ARTIFACT_ROOT: /mlflow-data/artifacts
    networks:
      - mlops-network
    ports:
      - "5000:5000"
    restart: always

networks:
  mlops-network:
    driver: bridge