services:
  trainer:
    build:
      context: .
      dockerfile: docker/train/Dockerfile
    container_name: rakuten_trainer
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./models:/app/models
    networks:
      - mlops-network
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_HOST=mlflow
      - MONGO_HOST=mongodb
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  predictor:
    build:
      context: .
      dockerfile: docker/predict/Dockerfile
    container_name: rakuten_predictor
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./models:/app/models
    networks:
      - mlops-network
    ports:
      - "8080:8080"
    environment:
      - MLFLOW_HOST=mlflow
      - MONGO_HOST=mongodb
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
