services:
  trainer:
    build:
      context: .
      dockerfile: docker/train/Dockerfile
    image: rakuten-trainer:latest
    container_name: rakuten_trainer
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./src:/app/src
    networks:
      - mlops-network
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    working_dir: /app

networks:
  mlops-network:
    driver: bridge
    name: mlops-network