version: "3.9"

services:
  predictor:
    build:
      context: .
      dockerfile: docker/predict/Dockerfile
    image: rakuten-predictor:latest
    container_name: rakuten_predictor
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./src:/app/src
      - ./models:/app/models:ro
    networks:
      - mlops-network
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  mlops-network:
    driver: bridge
    name: mlops-network