services:
  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow/Dockerfile
    container_name: mlops-mlflow
    volumes:
      - ./data/mlflow_artifacts:/mlflow_artifacts
      - ./data/mlflow.db:/mlflow.db
    networks:
      - mlops-network
    ports:
      - "5000:5000"
    restart: always

networks:
  mlops-network:
    driver: bridge