{
 "title": "FastAPI Observability",
 "description": "FastAPI dashboard for programs using FastAPI instrumented via prometheus_fastapi_instrumentator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(http_requests_total,job)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests Api Trainer",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"rakuten_trainer\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count Api Trainer",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"rakuten_trainer\", handler!=\"/metrics\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Total Requests Api Predictor",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"rakuten_predictor\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count Api Predictor",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"rakuten_predictor\", handler!=\"/metrics\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration Api Trainer",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"rakuten_trainer\"} / http_request_duration_seconds_count{job=\"rakuten_trainer\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"rakuten_predictor\"} / http_request_duration_seconds_count{job=\"rakuten_predictor\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests of Api Trainer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"rakuten_trainer\", status=~\"2.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"rakuten_trainer\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests of Api Predictor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"rakuten_predictor\", status=~\"2.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"rakuten_predictor\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests of Api Trainer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"rakuten_trainer\", status=~\"5.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"rakuten_trainer\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests of Api Predictor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"rakuten_predictor\", status=~\"5.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"rakuten_predictor\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}